FROM golang:1.9.2-alpine3.7

MAINTAINER Sergey Kudryashov <s.a.kudryashov@gmail.com>
RUN echo $GOPATH
COPY ./ /go/src/github.com/sKudryashov/asec
WORKDIR /go/src/github.com/sKudryashov/asec
RUN apk update && apk add build-base
RUN apk add sqlite

RUN go install -v github.com/sKudryashov/asec/fileserver/cmd/servd
RUN go install -v github.com/sKudryashov/asec/fileserver/cmd/servcli

ENTRYPOINT [ "servd" ]